# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EYKyuWDsgivZcADjZUMikmNiMIGGYUlO/protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/EYKyuWDsgivZcADjZUMikmNiMIGGYUlO/protobuf.proto\x12 eykyuwdsgivzcadjzumikmnimiggyulo\"+\n\x05State\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"~\n\x06Return\x12\x36\n\x05state\x18\x01 \x01(\x0b\x32\'.eykyuwdsgivzcadjzumikmnimiggyulo.State\x12<\n\x08\x65lements\x18\x02 \x01(\x0b\x32*.eykyuwdsgivzcadjzumikmnimiggyulo.Elements\"\x16\n\x05Input\x12\r\n\x05value\x18\x01 \x01(\t\"A\n\x06Inputs\x12\x37\n\x06inputs\x18\x01 \x01(\x0b\x32\'.eykyuwdsgivzcadjzumikmnimiggyulo.Input\"\x1a\n\tResponses\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"@\n\x05Serie\x12\x37\n\x06points\x18\x01 \x03(\x0b\x32\'.eykyuwdsgivzcadjzumikmnimiggyulo.Point\"@\n\x05Graph\x12\x37\n\x06series\x18\x01 \x01(\x0b\x32\'.eykyuwdsgivzcadjzumikmnimiggyulo.Serie\"A\n\x06Graphs\x12\x37\n\x06graphs\x18\x01 \x01(\x0b\x32\'.eykyuwdsgivzcadjzumikmnimiggyulo.Graph\"\xbe\x01\n\x08\x45lements\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.eykyuwdsgivzcadjzumikmnimiggyulo.Inputs\x12>\n\tresponses\x18\x02 \x01(\x0b\x32+.eykyuwdsgivzcadjzumikmnimiggyulo.Responses\x12\x38\n\x06graphs\x18\x03 \x01(\x0b\x32(.eykyuwdsgivzcadjzumikmnimiggyulo.Graphs\">\n\x02In\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.eykyuwdsgivzcadjzumikmnimiggyulo.Inputs2e\n\x06Server\x12[\n\x07\x65xecute\x12$.eykyuwdsgivzcadjzumikmnimiggyulo.In\x1a(.eykyuwdsgivzcadjzumikmnimiggyulo.Return0\x01\x62\x06proto3')



_STATE = DESCRIPTOR.message_types_by_name['State']
_RETURN = DESCRIPTOR.message_types_by_name['Return']
_INPUT = DESCRIPTOR.message_types_by_name['Input']
_INPUTS = DESCRIPTOR.message_types_by_name['Inputs']
_RESPONSES = DESCRIPTOR.message_types_by_name['Responses']
_POINT = DESCRIPTOR.message_types_by_name['Point']
_SERIE = DESCRIPTOR.message_types_by_name['Serie']
_GRAPH = DESCRIPTOR.message_types_by_name['Graph']
_GRAPHS = DESCRIPTOR.message_types_by_name['Graphs']
_ELEMENTS = DESCRIPTOR.message_types_by_name['Elements']
_IN = DESCRIPTOR.message_types_by_name['In']
State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.State)
  })
_sym_db.RegisterMessage(State)

Return = _reflection.GeneratedProtocolMessageType('Return', (_message.Message,), {
  'DESCRIPTOR' : _RETURN,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Return)
  })
_sym_db.RegisterMessage(Return)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Input)
  })
_sym_db.RegisterMessage(Input)

Inputs = _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
  'DESCRIPTOR' : _INPUTS,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Inputs)
  })
_sym_db.RegisterMessage(Inputs)

Responses = _reflection.GeneratedProtocolMessageType('Responses', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSES,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Responses)
  })
_sym_db.RegisterMessage(Responses)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Point)
  })
_sym_db.RegisterMessage(Point)

Serie = _reflection.GeneratedProtocolMessageType('Serie', (_message.Message,), {
  'DESCRIPTOR' : _SERIE,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Serie)
  })
_sym_db.RegisterMessage(Serie)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Graph)
  })
_sym_db.RegisterMessage(Graph)

Graphs = _reflection.GeneratedProtocolMessageType('Graphs', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHS,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Graphs)
  })
_sym_db.RegisterMessage(Graphs)

Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.Elements)
  })
_sym_db.RegisterMessage(Elements)

In = _reflection.GeneratedProtocolMessageType('In', (_message.Message,), {
  'DESCRIPTOR' : _IN,
  '__module__' : 'EYKyuWDsgivZcADjZUMikmNiMIGGYUlO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:eykyuwdsgivzcadjzumikmnimiggyulo.In)
  })
_sym_db.RegisterMessage(In)

_SERVER = DESCRIPTOR.services_by_name['Server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=85
  _STATE._serialized_end=128
  _RETURN._serialized_start=130
  _RETURN._serialized_end=256
  _INPUT._serialized_start=258
  _INPUT._serialized_end=280
  _INPUTS._serialized_start=282
  _INPUTS._serialized_end=347
  _RESPONSES._serialized_start=349
  _RESPONSES._serialized_end=375
  _POINT._serialized_start=377
  _POINT._serialized_end=406
  _SERIE._serialized_start=408
  _SERIE._serialized_end=472
  _GRAPH._serialized_start=474
  _GRAPH._serialized_end=538
  _GRAPHS._serialized_start=540
  _GRAPHS._serialized_end=605
  _ELEMENTS._serialized_start=608
  _ELEMENTS._serialized_end=798
  _IN._serialized_start=800
  _IN._serialized_end=862
  _SERVER._serialized_start=864
  _SERVER._serialized_end=965
# @@protoc_insertion_point(module_scope)
