# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyBCgzovMAicNgJKRaerdKVeezfzUPjv/protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SyBCgzovMAicNgJKRaerdKVeezfzUPjv/protobuf.proto',
  package='sybcgzovmaicngjkraerdkveezfzupjv',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/SyBCgzovMAicNgJKRaerdKVeezfzUPjv/protobuf.proto\x12 sybcgzovmaicngjkraerdkveezfzupjv\"+\n\x05State\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"~\n\x06Return\x12\x36\n\x05state\x18\x01 \x01(\x0b\x32\'.sybcgzovmaicngjkraerdkveezfzupjv.State\x12<\n\x08\x65lements\x18\x02 \x01(\x0b\x32*.sybcgzovmaicngjkraerdkveezfzupjv.Elements\"\x16\n\x05Input\x12\r\n\x05value\x18\x01 \x01(\t\"A\n\x06Inputs\x12\x37\n\x06inputs\x18\x01 \x01(\x0b\x32\'.sybcgzovmaicngjkraerdkveezfzupjv.Input\"\x1a\n\tResponses\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06Output\x12\r\n\x05value\x18\x01 \x01(\t\"D\n\x07Outputs\x12\x39\n\x07outputs\x18\x01 \x01(\x0b\x32(.sybcgzovmaicngjkraerdkveezfzupjv.Output\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\t\"@\n\x05Serie\x12\x37\n\x06points\x18\x01 \x03(\x0b\x32\'.sybcgzovmaicngjkraerdkveezfzupjv.Point\"@\n\x05Graph\x12\x37\n\x06series\x18\x01 \x03(\x0b\x32\'.sybcgzovmaicngjkraerdkveezfzupjv.Serie\"A\n\x06Graphs\x12\x37\n\x06graphs\x18\x01 \x01(\x0b\x32\'.sybcgzovmaicngjkraerdkveezfzupjv.Graph\"\xfa\x01\n\x08\x45lements\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.sybcgzovmaicngjkraerdkveezfzupjv.Inputs\x12>\n\tresponses\x18\x02 \x01(\x0b\x32+.sybcgzovmaicngjkraerdkveezfzupjv.Responses\x12:\n\x07outputs\x18\x03 \x01(\x0b\x32).sybcgzovmaicngjkraerdkveezfzupjv.Outputs\x12\x38\n\x06graphs\x18\x04 \x01(\x0b\x32(.sybcgzovmaicngjkraerdkveezfzupjv.Graphs\"x\n\x02In\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.sybcgzovmaicngjkraerdkveezfzupjv.Inputs\x12\x38\n\x06output\x18\x02 \x01(\x0b\x32(.sybcgzovmaicngjkraerdkveezfzupjv.Output2e\n\x06Server\x12[\n\x07\x65xecute\x12$.sybcgzovmaicngjkraerdkveezfzupjv.In\x1a(.sybcgzovmaicngjkraerdkveezfzupjv.Return0\x01\x62\x06proto3'
)




_STATE = _descriptor.Descriptor(
  name='State',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sybcgzovmaicngjkraerdkveezfzupjv.State.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='sybcgzovmaicngjkraerdkveezfzupjv.State.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=128,
)


_RETURN = _descriptor.Descriptor(
  name='Return',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Return.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elements', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Return.elements', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=256,
)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Input.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=280,
)


_INPUTS = _descriptor.Descriptor(
  name='Inputs',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Inputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Inputs.inputs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=347,
)


_RESPONSES = _descriptor.Descriptor(
  name='Responses',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Responses.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=375,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Output.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=400,
)


_OUTPUTS = _descriptor.Descriptor(
  name='Outputs',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Outputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='outputs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Outputs.outputs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=470,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Point.x', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Point.y', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=501,
)


_SERIE = _descriptor.Descriptor(
  name='Serie',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Serie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Serie.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=567,
)


_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='series', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Graph.series', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=569,
  serialized_end=633,
)


_GRAPHS = _descriptor.Descriptor(
  name='Graphs',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Graphs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Graphs.graphs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=700,
)


_ELEMENTS = _descriptor.Descriptor(
  name='Elements',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Elements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Elements.inputs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responses', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Elements.responses', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Elements.outputs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='graphs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.Elements.graphs', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=953,
)


_IN = _descriptor.Descriptor(
  name='In',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.In',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='sybcgzovmaicngjkraerdkveezfzupjv.In.inputs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='sybcgzovmaicngjkraerdkveezfzupjv.In.output', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=955,
  serialized_end=1075,
)

_RETURN.fields_by_name['state'].message_type = _STATE
_RETURN.fields_by_name['elements'].message_type = _ELEMENTS
_INPUTS.fields_by_name['inputs'].message_type = _INPUT
_OUTPUTS.fields_by_name['outputs'].message_type = _OUTPUT
_SERIE.fields_by_name['points'].message_type = _POINT
_GRAPH.fields_by_name['series'].message_type = _SERIE
_GRAPHS.fields_by_name['graphs'].message_type = _GRAPH
_ELEMENTS.fields_by_name['inputs'].message_type = _INPUTS
_ELEMENTS.fields_by_name['responses'].message_type = _RESPONSES
_ELEMENTS.fields_by_name['outputs'].message_type = _OUTPUTS
_ELEMENTS.fields_by_name['graphs'].message_type = _GRAPHS
_IN.fields_by_name['inputs'].message_type = _INPUTS
_IN.fields_by_name['output'].message_type = _OUTPUT
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Return'] = _RETURN
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['Inputs'] = _INPUTS
DESCRIPTOR.message_types_by_name['Responses'] = _RESPONSES
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
DESCRIPTOR.message_types_by_name['Outputs'] = _OUTPUTS
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Serie'] = _SERIE
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH
DESCRIPTOR.message_types_by_name['Graphs'] = _GRAPHS
DESCRIPTOR.message_types_by_name['Elements'] = _ELEMENTS
DESCRIPTOR.message_types_by_name['In'] = _IN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.State)
  })
_sym_db.RegisterMessage(State)

Return = _reflection.GeneratedProtocolMessageType('Return', (_message.Message,), {
  'DESCRIPTOR' : _RETURN,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Return)
  })
_sym_db.RegisterMessage(Return)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Input)
  })
_sym_db.RegisterMessage(Input)

Inputs = _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
  'DESCRIPTOR' : _INPUTS,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Inputs)
  })
_sym_db.RegisterMessage(Inputs)

Responses = _reflection.GeneratedProtocolMessageType('Responses', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSES,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Responses)
  })
_sym_db.RegisterMessage(Responses)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Output)
  })
_sym_db.RegisterMessage(Output)

Outputs = _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTS,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Outputs)
  })
_sym_db.RegisterMessage(Outputs)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Point)
  })
_sym_db.RegisterMessage(Point)

Serie = _reflection.GeneratedProtocolMessageType('Serie', (_message.Message,), {
  'DESCRIPTOR' : _SERIE,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Serie)
  })
_sym_db.RegisterMessage(Serie)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Graph)
  })
_sym_db.RegisterMessage(Graph)

Graphs = _reflection.GeneratedProtocolMessageType('Graphs', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHS,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Graphs)
  })
_sym_db.RegisterMessage(Graphs)

Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.Elements)
  })
_sym_db.RegisterMessage(Elements)

In = _reflection.GeneratedProtocolMessageType('In', (_message.Message,), {
  'DESCRIPTOR' : _IN,
  '__module__' : 'SyBCgzovMAicNgJKRaerdKVeezfzUPjv.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:sybcgzovmaicngjkraerdkveezfzupjv.In)
  })
_sym_db.RegisterMessage(In)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='sybcgzovmaicngjkraerdkveezfzupjv.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1077,
  serialized_end=1178,
  methods=[
  _descriptor.MethodDescriptor(
    name='execute',
    full_name='sybcgzovmaicngjkraerdkveezfzupjv.Server.execute',
    index=0,
    containing_service=None,
    input_type=_IN,
    output_type=_RETURN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
