# Generated by Django 3.0.2 on 2020-07-15 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(choices=[('stopped', 'Stopped'), ('deleted', 'Deleted'), ('building', 'Building'), ('active', 'Active')], default='building', max_length=10)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('proto', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=100)),
                ('protocol', models.TextField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('workdir', models.CharField(max_length=500, null=True)),
                ('file', models.CharField(max_length=100, null=True)),
                ('classname', models.CharField(max_length=100, null=True)),
                ('subscribers', models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='created', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('docker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='module.Docker')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('progress', models.CharField(max_length=30)),
                ('state', models.CharField(default='execute', max_length=20)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='module.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('len', models.CharField(default=0, max_length=1)),
                ('value', models.TextField()),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_type', to='module.Docker')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='module.Element')),
            ],
        ),
        migrations.CreateModel(
            name='ElementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('value', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Element')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='module.Experiment')),
            ],
        ),
    ]
