# Generated by Django 3.0.2 on 2020-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
