# Generated by Django 3.0.2 on 2020-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_docker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdata',
            name='example',
            field=models.BooleanField(default=False),
        ),
    ]
