# Generated by Django 3.0.2 on 2020-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_docker_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='state',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('deleted', 'Deleted'), ('building', 'Building'), ('active', 'Active')], default='building', max_length=10),
        ),
    ]
