# Generated by Django 2.2.5 on 2020-02-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20191218_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='x',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y',
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('y', models.FloatField(blank=True, max_length=100, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='module.Graph')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='module.GraphType')),
            ],
        ),
    ]
