# Generated by Django 2.2.5 on 2020-02-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20200209_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='x',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='y',
        ),
        migrations.AlterField(
            model_name='serie',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='module.Graph'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('y', models.FloatField(blank=True, max_length=100, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='module.GraphType')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='module.Serie')),
            ],
        ),
    ]
