# Generated by Django 3.0.2 on 2020-07-16 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_elementdata_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docker',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='docker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
