# Generated by Django 3.0.2 on 2020-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_remove_docker_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='ip',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
