# Generated by Django 3.0.2 on 2020-07-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20200716_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
