# Generated by Django 2.2.5 on 2020-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_remove_point_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
