# Generated by Django 3.0.2 on 2020-06-30 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20200629_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('value', models.TextField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Element')),
            ],
        ),
        migrations.RemoveField(
            model_name='graph',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='GraphType',
        ),
        migrations.RemoveField(
            model_name='point',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='output_file',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='response',
        ),
        migrations.DeleteModel(
            name='Graph',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
        migrations.AddField(
            model_name='elementdata',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='module.Experiment'),
        ),
    ]
