# Generated by Django 3.0.2 on 2020-07-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_docker_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='view',
            field=models.CharField(default='2', max_length=1),
            preserve_default=False,
        ),
    ]
