# Generated by Django 2.2.5 on 2020-04-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_experiment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
