# Generated by Django 3.0.2 on 2020-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_experiment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdata',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
