# Generated by Django 3.0.2 on 2020-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20200731_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='extensions',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
