# Generated by Django 3.0.2 on 2020-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_docker_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='background',
            field=models.CharField(default='hola.png', max_length=500),
            preserve_default=False,
        ),
    ]
