# Generated by Django 2.2.5 on 2020-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_docker_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='ip',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
