# Generated by Django 3.0.2 on 2020-08-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_docker_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='extensions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
