# Generated by Django 3.0.2 on 2020-06-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_elementdata_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdata',
            name='alias',
        ),
        migrations.AddField(
            model_name='elementdata',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
