# Generated by Django 3.0.2 on 2020-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0011_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='state',
            field=models.CharField(default='execute', max_length=20),
        ),
    ]
