# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO/protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO/protobuf.proto\x12 oqbjcmgqsvsrmkpauepjysqrhowbbppo\"+\n\x05State\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"~\n\x06Return\x12\x36\n\x05state\x18\x01 \x01(\x0b\x32\'.oqbjcmgqsvsrmkpauepjysqrhowbbppo.State\x12<\n\x08\x65lements\x18\x02 \x01(\x0b\x32*.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Elements\"\x16\n\x05Input\x12\r\n\x05value\x18\x01 \x01(\t\"A\n\x06Inputs\x12\x37\n\x06inputs\x18\x01 \x01(\x0b\x32\'.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Input\"\x1a\n\tResponses\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06Output\x12\r\n\x05value\x18\x01 \x01(\t\"D\n\x07Outputs\x12\x39\n\x07outputs\x18\x01 \x01(\x0b\x32(.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Output\"\xc0\x01\n\x08\x45lements\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Inputs\x12>\n\tresponses\x18\x02 \x01(\x0b\x32+.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Responses\x12:\n\x07outputs\x18\x03 \x01(\x0b\x32).oqbjcmgqsvsrmkpauepjysqrhowbbppo.Outputs\"x\n\x02In\x12\x38\n\x06inputs\x18\x01 \x01(\x0b\x32(.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Inputs\x12\x38\n\x06output\x18\x02 \x01(\x0b\x32(.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Output2e\n\x06Server\x12[\n\x07\x65xecute\x12$.oqbjcmgqsvsrmkpauepjysqrhowbbppo.In\x1a(.oqbjcmgqsvsrmkpauepjysqrhowbbppo.Return0\x01\x62\x06proto3')



_STATE = DESCRIPTOR.message_types_by_name['State']
_RETURN = DESCRIPTOR.message_types_by_name['Return']
_INPUT = DESCRIPTOR.message_types_by_name['Input']
_INPUTS = DESCRIPTOR.message_types_by_name['Inputs']
_RESPONSES = DESCRIPTOR.message_types_by_name['Responses']
_OUTPUT = DESCRIPTOR.message_types_by_name['Output']
_OUTPUTS = DESCRIPTOR.message_types_by_name['Outputs']
_ELEMENTS = DESCRIPTOR.message_types_by_name['Elements']
_IN = DESCRIPTOR.message_types_by_name['In']
State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.State)
  })
_sym_db.RegisterMessage(State)

Return = _reflection.GeneratedProtocolMessageType('Return', (_message.Message,), {
  'DESCRIPTOR' : _RETURN,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Return)
  })
_sym_db.RegisterMessage(Return)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Input)
  })
_sym_db.RegisterMessage(Input)

Inputs = _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
  'DESCRIPTOR' : _INPUTS,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Inputs)
  })
_sym_db.RegisterMessage(Inputs)

Responses = _reflection.GeneratedProtocolMessageType('Responses', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSES,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Responses)
  })
_sym_db.RegisterMessage(Responses)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Output)
  })
_sym_db.RegisterMessage(Output)

Outputs = _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTS,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Outputs)
  })
_sym_db.RegisterMessage(Outputs)

Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.Elements)
  })
_sym_db.RegisterMessage(Elements)

In = _reflection.GeneratedProtocolMessageType('In', (_message.Message,), {
  'DESCRIPTOR' : _IN,
  '__module__' : 'OqBJCMGQSVSRmKPaUepJYsqRhOWBBppO.protobuf_pb2'
  # @@protoc_insertion_point(class_scope:oqbjcmgqsvsrmkpauepjysqrhowbbppo.In)
  })
_sym_db.RegisterMessage(In)

_SERVER = DESCRIPTOR.services_by_name['Server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=85
  _STATE._serialized_end=128
  _RETURN._serialized_start=130
  _RETURN._serialized_end=256
  _INPUT._serialized_start=258
  _INPUT._serialized_end=280
  _INPUTS._serialized_start=282
  _INPUTS._serialized_end=347
  _RESPONSES._serialized_start=349
  _RESPONSES._serialized_end=375
  _OUTPUT._serialized_start=377
  _OUTPUT._serialized_end=400
  _OUTPUTS._serialized_start=402
  _OUTPUTS._serialized_end=470
  _ELEMENTS._serialized_start=473
  _ELEMENTS._serialized_end=665
  _IN._serialized_start=667
  _IN._serialized_end=787
  _SERVER._serialized_start=789
  _SERVER._serialized_end=890
# @@protoc_insertion_point(module_scope)
