# Generated by Django 2.2.5 on 2019-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='base_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docker',
            name='img_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docker',
            name='ip',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='docker',
            name='proto_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='input_file',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='output_file',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='response',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
