# Generated by Django 3.0.2 on 2020-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20200716_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
