# Generated by Django 3.0.2 on 2020-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20200723_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(default='/media/users/3.jpg', null=True),
        ),
    ]
