# Generated by Django 3.0.2 on 2020-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20200910_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(default='/media/users/default.png', null=True),
        ),
    ]
