# Generated by Django 3.0.2 on 2020-09-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20200910_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('developer', 'Developer'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
